OAUTH_PROVIDER_URL: "https://authz.dinero.dk/dineroapi"
OAUTH_REDIRECT_URI: "/oauth/callback"
API_KEY: "1f7ec76c2b4c418f802690a922d93226"
CLIENT_ID: "ALCO"
CLIENT_SECRET: "SAGqbeheya6gKvuSstUemHB0fwJteZPTUC75TMKpNI" 
BASE64_ENCODED_CLIENT_ID_AND_SECRET: "QUxDTzpTQUdxYmVoZXlhNmdLdnVTc3RVZW1IQjBmd0p0ZVpQVFVDNzVUTUtwTkk="

